# Projekt: Optimaler Standort für eine Elektro-Motorrad Messe in Zürich

### Ersteller/in:
<li> Fabian Pfister (T WB-T-CAS-INFE-2-24-17) </li>
<li> Perrine Rotzetter (T WB-T-CAS-INFE-2-24-17) </li>
<li> Stefan Schegg (T WB-T-CAS-INFE-2-24-17) </li>

Anmerkung: Damit das Skript läuft müssen die vorangegangenen Skripts kompiliert worden sein und ein Ordner "data" im gleichen Ordner wie das Skript existieren.\
Ordner "data": Hier ist die ursprüngliche Datengrundlage Gemeindedaten und Geodaten sowie Resultate vorheriger Skript abgespeichert.

## Importiere Bibliotheken

In [1]:
import pandas as pd

## Importiere Bearbeitete Daten

In [2]:
# Definiere Filepath
daten_path = "./data/df_gesamt.csv"
df_gesamt = pd.read_csv(daten_path)

## Erstelle Dataframe für Metrik

In [3]:
# Zuweisung des Bewertungsschemas
metrik_bev_jung = 0.03 # Bevölkerung: Anteil 20-39-Jährige [%]
metrik_bev_alt = 0.07 # Bevölkerung: Anteil 40-64-Jährige [%]
metrik_motorrad_pro_einwohner = 0.03 # Motorräder pro 1000 Einwohner [Anz.]
metrik_motorrad_neuzulassungen = 0.04 # Motorrad-Neuzulasssungen pro 1000 Einw. [Anz.]
metrik_weg_haltestelle = 0.1 # Weg zur nächsten Haltestelle [m]
metrik_MV_wege = 0.2 # MIV-Wege Quell-, Ziel- und Binnenverkehr [Anz.]
metrik_erschliessung_öv = 0.1 # Erschliessung durch S-Bahn+Bus [% der Einw.] 
metrik_ladestationen_anz = 0.1 # electric_car_charging_spot_count
metrik_auto_per_ladestationen = 0.1 # electric_cars_per_charging_spot
metrik_neuzulassungen_elektromotor = 0.15 # Neuzulassungen  Elektromotor [%] 
metrik_elektromotor_bestand = 0.05 # Bestand Elektromotor [%]
metrik_steuerbares_einkommen = 0.03

In [4]:
df_metrik = pd.DataFrame()

# Setze Eintrag 1 = Metrik und Eintrag 2 = Ranking-Method
df_metrik.at[1, 'Bevölkerung: Anteil 20-39-Jährige [%] '] = metrik_bev_jung
# Datentyp der Spalte zu 'object' ändern. So stellt es kein Problem mehr da dass im Dataframe verschiedene Datentypen vorhanden sind.
df_metrik['Bevölkerung: Anteil 20-39-Jährige [%] '] = df_metrik['Bevölkerung: Anteil 20-39-Jährige [%] '].astype(object)
# Ranking nach "min" oder "max" bewerten
df_metrik.at[2, 'Bevölkerung: Anteil 20-39-Jährige [%] '] = 'min'

df_metrik.at[1, 'Bevölkerung: Anteil 40-64-Jährige [%] '] = metrik_bev_alt
df_metrik['Bevölkerung: Anteil 40-64-Jährige [%] '] = df_metrik['Bevölkerung: Anteil 40-64-Jährige [%] '].astype(object)
df_metrik.at[2, 'Bevölkerung: Anteil 40-64-Jährige [%] '] = 'min'

df_metrik.at[1, 'Motorräder pro 1000 Einwohner [Anz.] '] = metrik_motorrad_pro_einwohner
df_metrik['Motorräder pro 1000 Einwohner [Anz.] '] = df_metrik['Motorräder pro 1000 Einwohner [Anz.] '].astype(object)
df_metrik.at[2, 'Motorräder pro 1000 Einwohner [Anz.] '] = 'min'

df_metrik.at[1, 'Motorrad-Neuzulasssungen pro 1000 Einw. [Anz.] '] = metrik_motorrad_neuzulassungen
df_metrik['Motorrad-Neuzulasssungen pro 1000 Einw. [Anz.] '] = df_metrik['Motorrad-Neuzulasssungen pro 1000 Einw. [Anz.] '].astype(object)
df_metrik.at[2, 'Motorrad-Neuzulasssungen pro 1000 Einw. [Anz.] '] = 'min'

df_metrik.at[1, 'Weg zur nächsten Haltestelle [m] '] = metrik_weg_haltestelle
df_metrik['Weg zur nächsten Haltestelle [m] '] = df_metrik['Weg zur nächsten Haltestelle [m] '].astype(object)
df_metrik.at[2, 'Weg zur nächsten Haltestelle [m] '] = 'min'

df_metrik.at[1, 'MIV-Wege Quell-, Ziel- und Binnenverkehr [Anz.] '] = metrik_MV_wege
df_metrik['MIV-Wege Quell-, Ziel- und Binnenverkehr [Anz.] '] = df_metrik['MIV-Wege Quell-, Ziel- und Binnenverkehr [Anz.] '].astype(object)
df_metrik.at[2, 'MIV-Wege Quell-, Ziel- und Binnenverkehr [Anz.] '] = 'min'

df_metrik.at[1, 'Erschliessung durch S-Bahn+Bus [% der Einw.] '] = metrik_erschliessung_öv
df_metrik['Erschliessung durch S-Bahn+Bus [% der Einw.] '] = df_metrik['Erschliessung durch S-Bahn+Bus [% der Einw.] '].astype(object)
df_metrik.at[2, 'Erschliessung durch S-Bahn+Bus [% der Einw.] '] = 'max'

df_metrik.at[1, 'electric_car_charging_spot_count'] = metrik_ladestationen_anz
df_metrik['electric_car_charging_spot_count'] = df_metrik['electric_car_charging_spot_count'].astype(object)
df_metrik.at[2, 'electric_car_charging_spot_count'] = 'min'

df_metrik.at[1, 'electric_cars_per_charging_spot' ] = metrik_auto_per_ladestationen
df_metrik['electric_cars_per_charging_spot'] = df_metrik['electric_cars_per_charging_spot' ].astype(object)
df_metrik.at[2, 'electric_cars_per_charging_spot' ] = 'max'

df_metrik.at[1, 'Neuzulassungen  Elektromotor [%] ' ] = metrik_neuzulassungen_elektromotor
df_metrik['Neuzulassungen  Elektromotor [%] '] = df_metrik['Neuzulassungen  Elektromotor [%] '].astype(object)
df_metrik.at[2, 'Neuzulassungen  Elektromotor [%] ' ] = 'min'

df_metrik.at[1, 'Bestand Elektromotor [%] ' ] = metrik_elektromotor_bestand
df_metrik['Bestand Elektromotor [%] ' ] = df_metrik['Bestand Elektromotor [%] ' ].astype(object)
df_metrik.at[2, 'Bestand Elektromotor [%] ' ] = 'min'

df_metrik.at[1, 'Ø steuerbares Einkommen natürliche Pers. [Fr.] ' ] = metrik_steuerbares_einkommen
df_metrik['Ø steuerbares Einkommen natürliche Pers. [Fr.] ' ] = df_metrik['Ø steuerbares Einkommen natürliche Pers. [Fr.] ' ].astype(object)
df_metrik.at[2, 'Ø steuerbares Einkommen natürliche Pers. [Fr.] ' ] = 'min'

## Analysiere Null-Werte und passe diese bei Bedarf an (-1 & 999)

In [5]:
df_gesamt[(df_gesamt == -1).any(axis=1)]

# -1 für Weg zur nächsten Haltestelle hat zur Folge, dass die betroffene Gemeinde die kleinste Punktzahl für dieses Attribut bekommt.

,bfs_nr,JAHR,Bevölkerung: Anteil 20-39-Jährige [%],Bevölkerung: Anteil 40-64-Jährige [%],Motorräder [Anz.],Motorräder pro 1000 Einwohner [Anz.],Bestand Elektromotor [%],Bevölkerung [Pers.],Ø steuerbares Einkommen natürliche Pers. [Fr.],Ø steuerbares Vermögen natürliche Pers. [Fr.],...,"MIV-Wege Quell-, Ziel- und Binnenverkehr [Anz.]",MIV-Anteil (Modal Split) [%],Motorrad-Neuzulassungen [Anz.],Motorrad-Neuzulasssungen pro 1000 Einw. [Anz.],Neuzulassungen Elektromotor [%],Weg zur nächsten Haltestelle [m],municipality,canton,electric_car_charging_spot_count,electric_cars_per_charging_spot
152,291,2023,21.3,36.0,344,100.4,3.9,3570,67084,492000000,...,-1.0,-1.0,15,4.4,29.6,-1.0,Andelfingen,ZH,7,15.6

In [6]:
df_gesamt[(df_gesamt == 999).any(axis=1)]

# 999 für electric_cars_charging_spot hat zur Folge, dass die betroffenen Gemeinden die kleinste Punktzahl für dieses Attribut bekommt.

,bfs_nr,JAHR,Bevölkerung: Anteil 20-39-Jährige [%],Bevölkerung: Anteil 40-64-Jährige [%],Motorräder [Anz.],Motorräder pro 1000 Einwohner [Anz.],Bestand Elektromotor [%],Bevölkerung [Pers.],Ø steuerbares Einkommen natürliche Pers. [Fr.],Ø steuerbares Vermögen natürliche Pers. [Fr.],...,"MIV-Wege Quell-, Ziel- und Binnenverkehr [Anz.]",MIV-Anteil (Modal Split) [%],Motorrad-Neuzulassungen [Anz.],Motorrad-Neuzulasssungen pro 1000 Einw. [Anz.],Neuzulassungen Elektromotor [%],Weg zur nächsten Haltestelle [m],municipality,canton,electric_car_charging_spot_count,electric_cars_per_charging_spot
0,1,2023,18.2,42.4,252,126.6,7.5,1995,86111,859000000,...,5232.0,83.0,4,2.0,37.5,213.0,Aeugst am Albis,ZH,0,999.0
4,5,2023,22.7,38.4,343,88.8,4.9,3941,78570,496000000,...,9127.0,73.0,23,6.0,27.4,259.0,Hedingen,ZH,0,999.0
5,6,2023,19.2,40.7,133,100.7,4.7,1322,72970,453000000,...,2982.0,97.0,6,4.5,32.1,208.0,Kappel am Albis,ZH,0,999.0
6,7,2023,21.1,37.7,201,83.4,6.3,2440,72943,378000000,...,5706.0,86.0,10,4.1,39.4,490.0,Knonau,ZH,0,999.0
7,8,2023,17.9,42.2,62,96.3,4.7,642,58041,425000000,...,2006.0,97.0,3,4.7,33.3,188.0,Maschwanden,ZH,0,999.0
11,12,2023,14.1,40.8,111,96.5,6.8,1145,75248,499000000,...,2528.0,90.0,6,5.2,47.6,210.0,Rifferswil,ZH,0,999.0
13,14,2023,18.3,37.6,476,90.1,7.3,5306,98510,726000000,...,9854.0,82.0,29,5.5,35.0,151.0,Wettswil am Albis,ZH,0,999.0
15,23,2023,18.6,39.1,90,152.0,2.3,601,97830,1898000000,...,1881.0,92.0,3,5.1,22.2,203.0,Berg am Irchel,ZH,0,999.0
16,24,2023,21.9,37.3,133,128.1,5.8,1032,67982,464000000,...,2710.0,93.0,9,8.7,15.6,143.0,Buch am Irchel,ZH,0,999.0
17,25,2023,19.9,38.8,225,115.3,6.1,1974,67553,429000000,...,4043.0,75.0,8,4.1,30.2,307.0,Dachsen,ZH,0,999.0
18,26,2023,24.0,38.7,110,154.5,4.5,721,67550,403000000,...,2157.0,90.0,8,11.2,25.0,219.0,Dorf,ZH,0,999.0
20,28,2023,24.9,35.7,163,110.6,4.9,1489,66223,408000000,...,4777.0,93.0,10,6.8,23.1,249.0,Flaach,ZH,0,999.0
21,29,2023,21.5,39.2,128,84.5,5.6,1510,73682,518000000,...,3924.0,96.0,4,2.6,46.7,376.0,Flurlingen,ZH,0,999.0
25,35,2023,21.9,35.4,230,118.1,3.0,1948,67851,453000000,...,7958.0,86.0,11,5.6,21.4,436.0,Marthalen,ZH,0,999.0
28,39,2023,19.2,40.4,155,158.3,4.6,1027,64296,387000000,...,2773.0,94.0,12,12.3,34.4,237.0,Thalheim an der Thur,ZH,0,999.0
29,40,2023,21.0,36.0,134,125.8,4.6,1090,59288,414000000,...,5380.0,96.0,3,2.8,38.9,212.0,Trüllikon,ZH,0,999.0
30,41,2023,19.7,40.3,43,92.7,6.8,471,59049,403000000,...,1208.0,91.0,3,6.5,50.0,247.0,Truttikon,ZH,0,999.0
31,43,2023,23.2,41.1,32,84.0,2.2,380,69317,384000000,...,1054.0,91.0,2,5.2,16.7,179.0,Volken,ZH,0,999.0
40,59,2023,21.2,36.2,198,99.3,3.0,1997,64606,333000000,...,4672.0,84.0,7,3.5,15.9,265.0,Hochfelden,ZH,0,999.0
42,61,2023,19.0,39.1,139,127.3,4.2,1108,70739,391000000,...,3620.0,94.0,11,10.1,28.6,284.0,Hüntwangen,ZH,0,999.0
44,63,2023,26.0,38.8,356,128.8,5.0,2841,77011,377000000,...,5500.0,86.0,22,8.0,22.7,259.0,Lufingen,ZH,0,999.0
46,65,2023,18.9,42.6,138,127.4,2.6,1079,73539,387000000,...,2665.0,89.0,11,10.2,23.8,515.0,Oberembrach,ZH,0,999.0
49,68,2023,24.1,38.6,280,96.3,2.8,3003,60911,252000000,...,8752.0,91.0,12,4.1,25.9,194.0,Rorbas,ZH,0,999.0
51,70,2023,19.4,37.8,83,141.4,3.8,577,62581,325000000,...,1754.0,88.0,7,11.9,14.3,164.0,Wasterkingen,ZH,0,999.0
58,85,2023,23.0,39.3,220,118.2,4.0,1864,68804,349000000,...,3377.0,81.0,7,3.8,33.3,228.0,Dänikon,ZH,0,999.0
60,87,2023,17.4,42.0,135,140.8,3.6,973,85209,473000000,...,1780.0,90.0,7,7.3,36.7,224.0,Hüttikon,ZH,0,999.0
61,88,2023,17.7,42.1,339,102.2,4.9,3314,9634,1404000000,...,13636.0,94.0,26,7.8,25.4,238.0,Neerach,ZH,0,999.0
62,89,2023,26.8,37.0,458,88.6,3.1,5325,60791,276000000,...,16124.0,84.0,31,6.0,18.5,208.0,Niederglatt,ZH,0,999.0
68,95,2023,15.8,44.9,30,64.4,2.5,463,75801,563000000,...,1335.0,85.0,1,2.1,33.3,120.0,Regensberg,ZH,0,999.0
71,98,2023,26.2,38.0,95,110.3,3.9,870,64244,345000000,...,1317.0,90.0,5,5.8,25.0,192.0,Schleinikon,ZH,0,999.0
72,99,2023,17.6,40.0,146,107.3,5.1,1389,73158,475000000,...,3056.0,82.0,7,5.1,20.4,231.0,Schöfflisdorf,ZH,0,999.0
73,100,2023,23.0,39.5,235,100.1,3.8,2359,64205,327000000,...,6897.0,91.0,10,4.3,23.2,292.0,Stadel,ZH,0,999.0
75,102,2023,29.0,37.5,214,103.2,3.5,2116,58069,237000000,...,7871.0,97.0,13,6.3,16.9,243.0,Weiach,ZH,0,999.0
81,116,2023,23.6,36.4,395,103.0,4.8,3837,64781,395000000,...,13519.0,91.0,23,6.0,26.4,296.0,Grüningen,ZH,0,999.0
90,137,2023,19.6,36.2,427,80.9,3.9,5385,96091,836000000,...,11619.0,70.0,18,3.4,30.7,203.0,Oberrieden,ZH,0,999.0
106,173,2023,20.8,39.2,416,110.8,3.5,3897,68372,347000000,...,11686.0,92.0,20,5.3,25.0,261.0,Hittnau,ZH,0,999.0
110,180,2023,21.4,37.0,387,112.7,4.9,3458,71416,490000000,...,9137.0,92.0,18,5.2,32.5,186.0,Weisslingen,ZH,0,999.0
111,181,2023,21.4,36.7,223,109.1,3.9,2079,56555,308000000,...,6050.0,90.0,14,6.8,25.0,279.0,Wila,ZH,0,999.0
112,182,2023,19.4,39.1,125,121.6,1.7,1025,68669,374000000,...,3547.0,93.0,10,9.7,10.0,275.0,Wildberg,ZH,0,999.0
116,194,2023,22.0,34.3,353,66.4,3.3,5384,73092,534000000,...,12068.0,67.0,14,2.6,26.1,207.0,Greifensee,ZH,0,999.0
123,211,2023,21.9,35.4,108,148.1,3.4,754,59442,319000000,...,1956.0,93.0,5,6.9,35.3,307.0,Altikon,ZH,0,999.0
124,213,2023,21.4,37.9,220,101.9,5.5,2182,84294,716000000,...,5585.0,89.0,13,6.0,34.5,229.0,Brütten,ZH,0,999.0
125,214,2023,22.7,39.2,131,119.9,6.0,1126,62402,346000000,...,2676.0,90.0,0,0.0,41.2,220.0,Dägerlen,ZH,0,999.0
126,215,2023,16.4,41.3,56,67.6,3.9,842,80925,825000000,...,1992.0,91.0,2,2.4,28.6,180.0,Dättlikon,ZH,0,999.0
130,220,2023,23.1,38.2,150,130.9,2.3,1163,60314,300000000,...,3245.0,92.0,4,3.5,4.8,515.0,Hagenbuch,ZH,0,999.0
131,221,2023,20.6,38.4,249,80.0,6.4,3219,80074,675000000,...,9186.0,87.0,11,3.5,38.6,218.0,Hettlingen,ZH,0,999.0
134,225,2023,21.1,35.8,300,108.3,3.6,2812,62386,407000000,...,7647.0,88.0,13,4.7,25.9,208.0,Rickenbach,ZH,0,999.0
135,226,2023,17.8,38.1,112,147.6,4.1,775,59038,361000000,...,2357.0,91.0,5,6.6,36.4,260.0,Schlatt,ZH,0,999.0
140,241,2023,22.1,37.6,191,114.9,7.9,1696,91213,664000000,...,4936.0,88.0,11,6.6,29.7,257.0,Aesch,ZH,0,999.0
148,249,2023,24.1,35.7,403,98.0,3.4,4298,75769,536000000,...,9755.0,88.0,18,4.4,14.6,213.0,Unterengstringen,ZH,0,999.0
149,250,2023,24.8,34.7,760,73.6,3.3,10390,61915,323000000,...,41867.0,83.0,31,3.0,13.5,191.0,Urdorf,ZH,0,999.0
155,294,2023,23.8,35.6,439,86.6,3.4,5111,60924,375000000,...,13697.0,88.0,37,7.3,23.5,342.0,Elgg,ZH,0,999.0

## Bewerte Daten mit Rängen

In [7]:
# finde gleiche Kolonnen
common_columns = df_gesamt.columns.intersection(df_metrik.columns)

# erstelle Dataframe
df_gesamt_ranked = pd.DataFrame()

# Sort values in common columns
for col in common_columns:
     # Methode aus df_metrik holen
    rank_method = df_metrik[col].iloc[1] 
    # Ascending für 'min', sonst 'max'
    ascending = True if rank_method == 'min' else False  
    # eigentliches ranking
    df_gesamt_ranked[col] = df_gesamt[col].rank(ascending=ascending, method='dense')

## Erstelle finale Bewertung

In [8]:
# erstelle Dataframe
df_result = pd.DataFrame()

# Bewerte Ranking nach der erstellten Metrik
#Iteriere durch alle Kolonnen beider dataframes
for i in range(0, len(df_gesamt_ranked.columns)):
    for j in range(0, len(df_metrik.columns)):
        # Wenn Kolonnen-Namen gleich, rechne Metrik * Spalte der Ranking-Tabelle
        if(df_gesamt_ranked.columns[i] == df_metrik.columns[j]):
            column_name = df_gesamt_ranked.columns[i]
            df_result[column_name] = df_metrik.iloc[0, j] * df_gesamt_ranked[column_name][:]

In [9]:
# erstelle Dataframe
df_ranking = pd.DataFrame()

# Summe pro Zeile berechnen und als neue Spalte hinzufügen
df_result['Ranking Gesamt [Punkte]'] = df_result.sum(axis=1)

# bfs_nr und municipality wird für die spätere Identifizierung der Gemeinden benötigt. 
df_result['bfs_nr'] = df_gesamt['bfs_nr']
df_result['municipality'] = df_gesamt['municipality']

df_result.head()

,Bevölkerung: Anteil 20-39-Jährige [%],Bevölkerung: Anteil 40-64-Jährige [%],Motorräder pro 1000 Einwohner [Anz.],Bestand Elektromotor [%],Ø steuerbares Einkommen natürliche Pers. [Fr.],Erschliessung durch S-Bahn+Bus [% der Einw.],"MIV-Wege Quell-, Ziel- und Binnenverkehr [Anz.]",Motorrad-Neuzulasssungen pro 1000 Einw. [Anz.],Neuzulassungen Elektromotor [%],Weg zur nächsten Haltestelle [m],electric_car_charging_spot_count,electric_cars_per_charging_spot,Ranking Gesamt [Punkte],bfs_nr,municipality
0,0.33,5.39,3.87,2.15,4.20,9.8,8.2,0.08,15.0,5.0,0.1,0.1,54.22,1,Aeugst am Albis
1,2.37,0.56,0.39,0.85,0.93,6.4,28.8,0.24,8.1,8.1,1.7,8.2,66.64,2,Affoltern am Albis
2,1.11,2.87,2.13,1.45,3.57,6.2,14.4,1.12,5.7,4.1,0.4,2.6,45.65,3,Bonstetten
3,0.39,4.27,2.85,1.50,3.12,9.8,10.4,1.16,9.9,6.6,0.5,4.8,55.29,4,Hausen am Albis
4,1.44,3.57,1.74,1.45,3.93,1.0,12.2,1.56,9.6,7.8,0.1,0.1,44.49,5,Hedingen

In [10]:
# Füge eine Rangliste anhand des erstellten Rankings hinzu.
df_result["Rangliste"] = df_result["Ranking Gesamt [Punkte]"].rank(ascending=False, method='dense')

## Ausgabe des resultierenden Files

In [11]:
#Zwischenspeicherung
df_result.to_csv("./data/df_ranking.csv", index=False)